<?php
declare(strict_types=1);

namespace prime\components;


use Box\Spout\Common\Entity\Style\Style;

class StyleMerger extends \Box\Spout\Writer\Common\Manager\Style\StyleMerger
{
    public function merge(Style $style, Style $baseStyle)
    {
        return $baseStyle;
        return parent::merge($style, $baseStyle); // TODO: Change the autogenerated stub
    }


}