before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - mkdir -p ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - composer config -g cache-dir .composercache
   - composer config cache-dir .composercache
   - composer config cache-dir
   - composer config cache-files-dir
stages:
  - test
cache:
  paths:
    - .composercache
#test:5.6:
#  image: php:5.6
#  script:
#  - php composer.phar exec codecept run
test:7.0:
  image: sammousa/php-with-extensions:7.0
  script:
    - composer -n install
#    - composer exec codecept run
