before_script:
   - curl -sS https://getcomposer.org/installer | php
   - php composer.phar install --dev
   - docker-php-ext-install imagick
   - docker-php-ext-install bz2
stages:
  - build
  - test
test:5.6:
  image: php:5.6
  script:
  - php composer.phar exec codecept run
test:7.0:
  image: php:7.0
  script:
  - php composer.phar exec codecept run