before_script:
   - apt-get update
   - apt-get -y install libmagickwand-dev libbz2-dev git --no-install-recommends
   - pecl install imagick
   - docker-php-ext-enable imagick
   - docker-php-ext-install bz2
   - docker-php-ext-install gd
   - curl -sS https://getcomposer.org/installer | php
   - php composer.phar install --dev
stages:
  - build
  - test
test:5.6:
  image: php:5.6
  script:
  - php composer.phar exec codecept run
test:7.0:
  image: php:7.0
  script:
  - php composer.phar exec codecept run