before_script:
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$SSH_PRIVATE_KEY")
   - php composer.phar -n install
stages:
  - build
  - test
#test:5.6:
#  image: php:5.6
#  script:
#  - php composer.phar exec codecept run
test:7.0:
  image: sammousa/php-with-extensions:7.0
  script:
  - php composer.phar exec codecept run