language: generic
jobs:
  include:
    - stage: "I18n"
      name: "Push translations"
      install:
        - eval "$(ssh-agent -s)"
        - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in priv.key.enc -d | ssh-add -
        - composer global require hirak/prestissimo  > /dev/null
        - git clone git@github.com:WorldHealthOrganization/herams-i18n.git  > /dev/null
        - pip install --user sphinx-intl > /dev/null
      script:
        - composer install
        - protected/yiic message/extract protected/config/i18n.php --message-path herams-i18n
        - sphinx-build -b gettext docs herams-i18n
        - cd herams-i18n
        # Fix bad Yii header in pot file by copying header from another file
        - (echo 'msgid ""'; echo 'msgstr ""'; grep '^"' guide.pot; tail -n +12 messages.pot) > app.pot
        - rm messages.pot
        - sphinx-intl update -p .
        - git add .
        - git commit -a -m "Update translation templates"
        - git push

#install:
#  - cp .env.default .env
#  - docker-compose --version
#  - docker-compose build
#before_script:
#  - docker-compose run --rm composer install
#script:
#  - docker-compose run --rm codeception run --coverage-xml
#after_script:
#  - docker run --rm -v $(pwd):$(pwd) --entrypoint /bin/sh php:alpine -c "cd $(pwd) && apk add --update --no-cache git && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml"