language: minimal
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - cp .env.default .env
  - docker-compose --version
  - docker-compose build
before_script:
  - docker-compose run --rm composer install
script:
  - docker-compose run --rm codeception run --coverage-xml
after_script:
  - docker run --rm --entrypoint /bin/sh php:alpine -v tests/_output/coverage.xml:/coverage.xml -c "wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar --format=php-clover /coverage.xml"