language: minimal
before_script:
  - docker-compose build
  - docker-compose composer install
script:
  - docker-compose run codeception --coverage-xml
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml