
version: '2.1'
services:

## Web server
  web:
    image: "sammousa/php-with-extensions"
    command: "php -S 0.0.0.0:80 -t /project/public"
    depends_on:
      - mysql
    volumes:
      - .:/project
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test
      DB_HOST: mysql
    ports:
      - "80"

## Mysql server (local)
  mysql:
    image: mysql
    command: --character-set-server=utf8 --max-connections=1000 --default-authentication-plugin=mysql_native_password
    user: "${UID}:${GID}"
    volumes:
      - ./local/devdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test

  cli:
    build:
      context: docker/cli
    depends_on:
      - mysql
    volumes:
      - .:/project:ro
      - ./protected/migrations:/project/protected/migrations:rw
    tmpfs:
      - /project/protected/runtime:rw,noexec,nosuid,uid=${UID}
      - /project/public/assets:rw,noexec,nosuid,uid=${UID}
    environment:
      YII_ENV: "dev"
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: test
      DB_HOST: mysql
    entrypoint: ["/sbin/tini", "--", "/project/protected/yiic"]
    user: "${UID}:${GID}"
    command: ""
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "12346:80"
    tmpfs:
      - /sessions