version: '3.8'
volumes:
  assets:
    driver_opts:
      type: tmpfs
      o: "uid=65534"
      device: "/docker/example"

x-env:



  base: &base
    build:
      context: docker/php
    volumes:
      - .:/project:ro
      - ./tests:/project/tests:rw
      - ./protected/migrations:/project/protected/migrations:rw
      - ./protected/messages:/project/protected/messages:rw
    tmpfs:
      - /runtime:rw,noexec,nosuid,uid=${UID-0}
      - /tmp:rw,noexec,nosuid,uid=${UID-0}
      - /project/public/assets:rw,noexec,nosuid,uid=${UID-0}
    environment:
      DB_HOST: devdb
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      YII_ENV: $YII_ENV
      LS_HOST: ${LS_HOST}
      LS_PASS: ${LS_PASS}
      LS_USER: ${LS_USER}
      RUNTIME_PATH: /runtime
      SMTP_HOST: mailcatcher
      RESPONSE_SUBMISSION_KEY: ${RESPONSE_SUBMISSION_KEY}
      URL_SIGNING_SECRET: ${URL_SIGNING_SECRET}
      PRIVATE_KEY_FILE: /project/local/testkey
      SMTP_PORT: 1025
    user: ${UID-0}:${GID-0}

    working_dir: "/project"
  mysql: &mysql
    image: mysql
    command: --character-set-server=utf8mb4 --max-connections=1000 --default-authentication-plugin=mysql_native_password
    user: ${UID-0}:${GID-0}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
services:
  phpfpm:
    environment:
      DB_HOST: devdb
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      YII_ENV: $YII_ENV
      LS_HOST: ${LS_HOST}
      LS_PASS: ${LS_PASS}
      LS_USER: ${LS_USER}
      COOKIE_VALIDATION_KEY: ${COOKIE_VALIDATION_KEY}
      RUNTIME_PATH: /run
      SMTP_HOST: mailcatcher
      RESPONSE_SUBMISSION_KEY: ${RESPONSE_SUBMISSION_KEY}
      URL_SIGNING_SECRET: ${URL_SIGNING_SECRET}
      PRIVATE_KEY_FILE: /project/local/testkey
      SMTP_PORT: 1025
    depends_on:
      - devdb
      - mailcatcher
      - phpmyadmin
    build:
      context: docker/php
    volumes:
      - type: bind
        source: ./
        target: /project
      - type: volume
        source: assets
        target: /project/public/assets
  nginx:
    image: nginx
    environment:
      PHPFPM: "phpfpm:9000"
      RESOLVER: "127.0.0.11"
    depends_on:
      - phpfpm
    ports:
      - "0.0.0.0:12346:80"
    volumes:
      - type: bind
        source: ./protected/config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./public
        target: /www
      - type: volume
        source: assets
        target: /www/assets
        read_only: true
        volume:
          nocopy: true
  ## Mysql server (local), this will create a persistent data store for local development
  devdb:
    << : *mysql
    volumes:
      - ./local/devdb:/var/lib/mysql:rw
      - ./tests/_data/db:/docker-entrypoint-initdb.d:ro

  # Mysql server (testing), this will store data on tmpfs, it will not persist
  testdb:
    << : *mysql
    volumes:
      - ./tests/_data/db:/docker-entrypoint-initdb.d:ro
    tmpfs:
      /var/lib/mysql:rw,nodev,nosuid,relatime,uid=${UID-0}
  cli:
    << : *base
    depends_on:
      - devdb
      - mailcatcher
      - phpmyadmin
    entrypoint: ["/project/protected/yiic"]
    init: true
    command: ""
  testcli:
    <<: *base
    depends_on:
      - testdb
    entrypoint: ["/project/protected/yiic"]
    init: true
    command: ""
    environment:
      DB_HOST: testdb
      SECRET_database/username: $DB_USER
      DB_NAME: $DB_NAME
      SECRET_database/password: $DB_PASS
      YII_ENV: $YII_ENV
      RUNTIME_PATH: /runtime
  composer:
    << : *base
    init: true
    entrypoint: ["composer"]
    volumes:
      - /composer-cache
      - .:/project:rw
  codeception:
    << : *base
    depends_on:
      - testdb
    init: true
    entrypoint: [
      "sh",
      "-c",
      "wait4ports -s 30 tcp://testdb:3306 && exec /project/vendor/bin/codecept $$*",
      "-"
    ]
    command: "run"
    environment:
      DB_HOST: testdb
      SECRET_database/username: $DB_USER
      DB_NAME: $DB_NAME
      SECRET_database/password: $DB_PASS
      YII_ENV: $YII_ENV
      SECRET_app/url_signer_secret: secret
      SECRET_app/cookie_validation_key: secret
      RUNTIME_PATH: /runtime
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - devdb
    environment:
      PMA_HOSTS: testdb,devdb
      PMA_PASSWORD: $DB_PASS
      PMA_USER: $DB_USER
    ports:
      - "127.0.0.1:${PHPMYADMIN_PORT-12345}:80"
    tmpfs:
      - /sessions
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "127.0.0.1:${MAILCATCHER_PORT-12347}:1080"