version: '3.8'
networks:
  devproxy:
    external:
      name: devproxy
volumes:
  devdb:
  assets:
    driver_opts:
      type: tmpfs
      o: "uid=65534"
      device: "/docker/example"

x-env:
  base: &base
    build:
      context: docker/php
    volumes:
      - .:/project:rw
      - ./tests:/project/tests:rw
      - ./protected/migrations:/project/protected/migrations:rw
      - ./protected/messages:/project/protected/messages:rw
    tmpfs:
      - /runtime:rw,noexec,nosuid,uid=${UID-0}
      - /tmp:rw,noexec,nosuid,uid=${UID-0}
      - /project/public/assets:rw,noexec,nosuid,uid=${UID-0}
    environment:
      SECRET_database/dsn: "mysql:host=devdb;port=3306;dbname=${DB_NAME}"
      SECRET_database/username: ${DB_USER}
      SECRET_database/password: ${DB_PASS}
      YII_ENV: $YII_ENV
      SECRET_limesurvey/host: ${LS_HOST}
      LS_PASS: ${LS_PASS}
      LS_USER: ${LS_USER}
      RUNTIME_PATH: /runtime
      RESPONSE_SUBMISSION_KEY: ${RESPONSE_SUBMISSION_KEY}
      URL_SIGNING_SECRET: ${URL_SIGNING_SECRET}
      PRIVATE_KEY_FILE: /project/local/testkey
      SECRET_smtp/host: mailcatcher
      SECRET_smtp/port: 1025
      SECRET_smtp/encryption: tcp
    user: ${UID-0}:${GID-0}
    working_dir: "/project"
  mysql: &mysql
    image: mysql
    command: --character-set-server=utf8mb4 --max-connections=1000 --default-authentication-plugin=mysql_native_password
    user: ${UID-0}:${GID-0}
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
services:
  phpfpm:
    environment:
      SECRET_database/dsn: "mysql:host=devdb;port=3306;dbname=${DB_NAME}"
      SECRET_database/username: ${DB_USER}
      SECRET_database/password: ${DB_PASS}
      SECRET_app/cookie_validation_key: secret
      SECRET_app/url_signer_secret: secret
      YII_ENV: $YII_ENV
      SECRET_limesurvey/host: ${LS_HOST}
      SECRET_limesurvey/password: ${LS_PASS}
      SECRET_limesurvey/username: ${LS_USER}
      SECRET_limesurvey/sso_private_key: ${LS_PRIV_KEY}
      RUNTIME_PATH: /run
      RESPONSE_SUBMISSION_KEY: ${RESPONSE_SUBMISSION_KEY}
      URL_SIGNING_SECRET: ${URL_SIGNING_SECRET}
      smtp/host: mailcatcher
      smtp/port: 1025
    depends_on:
      - devdb
      - mailcatcher
      - phpmyadmin
    build:
      context: docker/php
    volumes:
      - type: bind
        source: ./
        target: /project
      - type: volume
        source: assets
        target: /project/public/assets
  coverage:
    labels:
      com.awesam.proxy.domains: "coverage.herams"
    networks:
      - devproxy
      - default
    image: nginx
    volumes:
      - ./tests/_output/coverage:/usr/share/nginx/html:ro
  nginx:
    labels:
      com.awesam.proxy.domains: "herams"
    networks:
      - devproxy
      - default
    image: nginx
    environment:
      PHPFPM: "phpfpm:9000"
      RESOLVER: "127.0.0.11"
    depends_on:
      - phpfpm
      - coverage
    ports:
      - "0.0.0.0:12346:80"
    volumes:
      - type: bind
        source: ./protected/config/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        source: ./public
        target: /www
      - type: bind
        source: ./node_modules
        target: /www/node_modules
      - type: volume
        source: assets
        target: /www/assets
        read_only: true
        volume:
          nocopy: true
  ## Mysql server (local), this will create a persistent data store for local development
  devdb:
    << : *mysql
    volumes:
      - devdb:/var/lib/mysql:rw
      - ./tests/_data/db:/docker-entrypoint-initdb.d:ro

  # Mysql server (testing), this will store data on tmpfs, it will not persist
  testdb:
    image: mysql
    command: --character-set-server=utf8mb4 --max-connections=1000
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./tests/_data/db:/docker-entrypoint-initdb.d:ro
    tmpfs:
      - /var/lib/mysql:rw,nodev,nosuid,relatime
  cli:
    << : *base
    depends_on:
      - devdb
      - mailcatcher
      - phpmyadmin
    entrypoint: ["/project/protected/yiic"]
    init: true
    command: ""
  testcli:
    <<: *base
    depends_on:
      - testdb
    entrypoint: ["/project/protected/yiic"]
    init: true
    command: ""
    environment:
      SECRET_database/dsn: "mysql:host=testdb;port=3306;dbname=${DB_NAME}"
      SECRET_database/username: $DB_USER
      SECRET_database/password: $DB_PASS
      YII_ENV: $YII_ENV
      RUNTIME_PATH: /runtime
  composer:
    << : *base
    init: true
    entrypoint: ["composer"]
    volumes:
      - /composer-cache
      - .:/project:rw
  codeception:
    << : *base
    depends_on:
      - testdb
    init: true
    entrypoint: [
      "sh",
      "-c",
      "wait4ports -s 30 tcp://testdb:3306 && exec /project/vendor/bin/codecept $$*",
      "-"
    ]
    command: "run"
    environment:
      SECRET_database/dsn: "mysql:host=testdb;port=3306;dbname=${DB_NAME}"
      SECRET_database/username: $DB_USER
      SECRET_database/password: $DB_PASS
      YII_ENV: $YII_ENV
      SECRET_app/url_signer_secret: secret
      SECRET_app/cookie_validation_key: secret
      RUNTIME_PATH: /runtime
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - devproxy
      - default
    labels:
      com.awesam.proxy.domains: "phpmyadmin.herams"
    depends_on:
      - devdb
    environment:
      PMA_HOSTS: testdb,devdb
      PMA_PASSWORD: $DB_PASS
      PMA_USER: $DB_USER
    ports:
      - "127.0.0.1:${PHPMYADMIN_PORT-12345}:80"
    tmpfs:
      - /sessions
  mailcatcher:
    image: schickling/mailcatcher
    networks:
      - devproxy
      - default
    labels:
      com.awesam.proxy.domains: "mailcatcher-herams"
      com.awesam.proxy.port: "1080"
    ports:
      - "127.0.0.1:${MAILCATCHER_PORT-12347}:1080"