<?php

namespace prime\models\forms\user;

use dektrium\user\models\RecoveryForm;

class Recovery extends RecoveryForm
{
    /**
     * @var string
     */
    public $captcha;
    public $confirmPassword;

    public function scenarios()
    {
        $result = parent::scenarios(); // TODO: Change the autogenerated stub
        $result['request'] = ['email', 'captcha'];
        $result['reset'] = ['password', 'confirmPassword'];
        return $result;
    }

    public function rules()
    {
        $result = parent::rules();
        $result[] = ['captcha', 'required'];
        $result[] = ['captcha', 'captcha'];
        $result[] = ['confirmPassword', 'required'];
        $result[] = ['confirmPassword', 'compare', 'compareAttribute' => 'password'];
        return $result;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        $result = parent::attributeLabels();
        return array_merge($result,
            [
                'confirmPassword' => \Yii::t('app', 'Confirmation')
            ]
        );
    }
}