{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "app",
    "namespace": "staging-v2",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "app",
        "namespace": "staging-v2",
        "creationTimestamp": null,
        "managedFields": [
          {
            "manager": "Go-http-client",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2022-07-08T13:27:41Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:data": {
                ".": {},
                "f:cookie_validation_key": {},
                "f:url_signer_secret": {}
              },
              "f:metadata": {
                "f:ownerReferences": {
                  ".": {},
                  "k:{\"uid\":\"f8e79565-dfa8-4f79-ab24-29ea4a3351a8\"}": {
                    ".": {},
                    "f:apiVersion": {},
                    "f:controller": {},
                    "f:kind": {},
                    "f:name": {},
                    "f:uid": {}
                  }
                }
              },
              "f:type": {}
            }
          }
        ]
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "cookie_validation_key": "AgDGyYv4Npc0hORSciIwf5tqbNj55aHBK6gR6XmYOYvScLyjZw+LRh39J2/9BkEDMXuR4kZLN5EaRU5u52e/MK9YPO98S4dM1sFBZl634dQZwcWNtC9f2Nfl9gYRlnJyZBPzdL15BhZX4cknKDj+ciEsB8U/Q4okYb2hbhdcR5wLar91jM6nI8vAJLu/k2/52FZn/smqX69EHYAe9c2lQn1NOgosgn6VGZ9MSAGoJuj1XOPsT3s+KjHXfVQvLe/gAAEJvtksgatC4iu3NwOJPicvae8VmzglJoP8OeFjXDVrE5d+nvBlFdSEklGCZrQ/NZJknKg2tppgqGBs+ARutbFGaCUTvq+HdF2bDugXoLVS+r3AfUkgbRwYeDHjk5OnMCc0KsqzEgzF5IDH/eZmFiDUh2ZF+oFRcTnfPNJpmv+YosBF3ct1XyE4+bKsJe4FCfTGvI0LfynO7pCDAqGH2as//e5IXGkQkcTPB1o2YWrwf8W4ZZP/94NPfAcB7lkWVT6L8HuuX+/F8apK7JKShr/vIjwJHokvTEW7kkouvk1eI0vK1QkPo3EJWsyilR+K7S0xICI6YmggQ6cLLA25pVWlGK4DvhQ0lCAceG2KgsuhapBrHL9nxrRNKSooiB/t3/PLE/+yVXjD4B0S4Gr64l90XfwRyU8JDbVc/ufQDQ6K6d16T575BRyikfW9Qjw4nJRhmL8aFEYem0bncexROxQhZ2KTpCDKbyndoO+5GQY7bdVzcc7KNw38kHtBle9frGY3vuIyZbU+Q8rNg6YX+AMaTeLSDEpjNd3BJ5BiYc7gbaUXizWL/YEhlWEFGREe7bs7Ql8EDre28Ynk9AnKV5xTIUCV5KwAMXtVhN5VeNhzRw==",
      "url_signer_secret": "AgApyFcVcn5VaWBbI26L7oyurSQ7ivvcB6MFjtoOr+leLMFXfIKfBRo2JxyBi5j3jdj2oSRSxYAXcinvG09CwhCHWhWzT60HwkPeHMmvde8baUHb1YYowrvAD4edbLg2Ul7HCGfn+CGrmfQj8TJAp3Q0NeAMqszq+0lQbAa6WqhNDVBN7ASzP3iue6uhG5aazidI32m4xCDX6RetjQmA76PWT0My2D6IJIVNQYEYjS2URhEEjYGfTjHRVFfoIYF9g7dtaU1YsZVO96uLOEf/EO7/8KUnoefqTaTtjaJgirsS1iqsOqquhfzngjGvb0eCN9hilRViDiIO+FuEGeUlAdby50g0SXK5aCX2nYohnLO4bDFbdrObW27MKH9BfrGdGWIUo3eT5ciWNuFlfWCuM80QewTFvBZgEpVWDv8C7hGLX0VJRwfRPLzTM2N1oaOMn7yYKUKCpqdZbc+deCwcjBd9W41d7N9O7mSsl6ul8hbLjHUCuytI8eYKbg/rQPhmAImX813t6NYg9HVkt1nHRaiEz75pmdwBv4+/lxEYriZjiZ2NktWGx7VejoTDCzrSoiGMJLl3lPw4x3yJrQ0Gim6v028+hxBpQEz+pVPM3hvnw694Cfd/UEYA9r/0V1s9mtN1GyGhkKbXs3hxSmmXra8SGnPpsxAarDmdrxUw+p5VaVNGSP+Ld9eiNWhBd5dFH42kWIOsYuP9Hu0I0/Rv2c/+Pzrh1JqIx0dy5ocsuIS9aeUcs3XucMhjV1+hpFKhsmfV074aUu/44bcxI3aJuNUVa3Hw0CArlGY5vxFAbQoexm+v3CWLBhGpNNdln1WaTbPW2kYHo3JXraxv8GnmgkVn9icyHYBeW7R9M80pA2v/vg=="
    }
  }
}
