# First, create a ConfigMap whose contents are used
# as the nginx.conf file in the web server. 
# This server uses /var/www/html as its
# root document directory. When the server gets a 
# request for *.php, it will forward that request
# to our PHP-FPM container.

kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {

    }

    http {
      include /etc/nginx/mime.types;
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;

          root /var/www/html;

          client_max_body_size 10m;

          try_files $uri @php;

          location = /status {
              return 200 'Nginx is up';
          }
          location ^~ /assets/ {
              access_log off;
              try_files $uri =404;
          }

          location = /favicon.ico {
              access_log off;
              return 404;
          }

          #PHP CONFIG
          location @php {
              fastcgi_param  SCRIPT_FILENAME    /project/public/index.php;
              fastcgi_param  QUERY_STRING       $query_string;
              fastcgi_param  REQUEST_METHOD     $request_method;
              fastcgi_param  CONTENT_TYPE       $content_type;
              fastcgi_param  CONTENT_LENGTH     $content_length;

              fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
              fastcgi_param  REQUEST_URI        $request_uri;
              fastcgi_param  DOCUMENT_URI       $document_uri;
              fastcgi_param  DOCUMENT_ROOT      $document_root;
              fastcgi_param  SERVER_PROTOCOL    $server_protocol;
              fastcgi_param  REQUEST_SCHEME     $scheme;
              fastcgi_param  HTTPS              $https if_not_empty;

              fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
              fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

              fastcgi_param  REMOTE_ADDR        $remote_addr;
              fastcgi_param  REMOTE_PORT        $remote_port;
              fastcgi_param  SERVER_ADDR        $server_addr;
              fastcgi_param  SERVER_PORT        $server_port;
              fastcgi_param  SERVER_NAME        $server_name;

              # PHP only, required if PHP was built with --enable-force-cgi-redirect
              fastcgi_param  REDIRECT_STATUS    200;

              fastcgi_read_timeout 300s;

              fastcgi_pass 127.0.0.1:9000;
              add_header X-Fastcgi 1 always;
          }
      }
    }
