apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          command:
            - redis-server
            - --appendonly
            - yes
            - --aclfile
            - /run/secrets/users.acl
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: acl
              mountPath: /run/secrets/
            - mountPath: /data
              name: redis-pvc
              subPath: data
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
        - name: acl
            secret:
              secretName: redis-acl
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
