apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app
  namespace: prod
spec:
  encryptedData:
    cookie_validation_key: AgAmBWKDkzZ+CQjBImDjo4Ai59lid0HoZih5EQ+9Km6fTTc37axEGbaCvoPmuCMwP6/3URZVJLEIckRpjZoN2iZ7a4y6ea6uHAS//j2RxEltNWJnSwCZEu7FxpZ6H4Vyg6+9e10YU7OctMx6zSM0uRRn2eeb+UNGJFljG/DCBIxYSfL3Q802p2VJOnOfBEfSOwGKUvjSVN2AsXxjy5KQp1lx1jLlE5pPSkpaYrY3JXLcmTSwV5P/HRxpyDnBE+DfsAVXEJA8ieKNDoGRoh93CmpFGzV+oVMRehHzFgjpxgyM5dBOxZDkaanUyvNoNLKT6JDuSrE9xOqEMEcYNc9eycvBJED2J1tLAkdzl06qwIKxu5yrZhovmo33TTjslPMQ3hBDgNlHjo8k+QA3eCjCn4pBQIH6j2LiMBeEQuqZiZJI2ey8KzgC5/sxnrfu5aTOo4J5r/ZXnicnNmZsA8evWppf/Fipbw39wluF8/uyNKFZ36bNbDGwZGpO0d0RwaZXZwN46PtXBkdCkM6S+/rIuQVoVa62jrDeLWzIyyT9Vboumk+IsZ8yb0W52jXILaxVjuy8masAGnanBW0l84Qek2LFw8C+apMYOUQPq1mxNokmQz9S+qYKDRK3goc8c8daxilSndckgsIZ+k2ppwESrc+I0oAlJDLNCblBFKtiNhhKqPPOOqF81T8NVOBPiFtnQfCT7foYno161372l6gskzCfT2DrSeexIFRW1geq5ePeMiViuc2/MKM1pPCOFAblJYArOISkPlm/iAXAiERflsO5W0Ldj88mVt798DRkLkcJyG0fLSDixkP5vagFzHQfULW2YkVlC2POOFjV1pdGbiNZ8bnhdtb+Uc5lbkzUXvV9dg==
    url_signer_secret: AgCYtAeRLlwyyG3DLFBk1zCkBvs4Vldblwq/fpaWAu/TFWQbf+OgTVoucf/PLPrRgfDCpMw+EwyoSWd/5Kg2EOdhpIezrvKMR5rk4mNuqq92yLUTWZ3fic6cOKMvy3RsVETGJ8GqyFGIJVIKN3BmwnMz0lOsxp3AMq9i3r+imAy1Xzb+rqCZmpt0nJQcuZ0VYQBjeSV8VOPFKFxrL4doZGrSTLE+BtMgHysNVivtKtyyX8KnG3T6hRz/hEfyEyDSCZOFJghRO4GzcjPuHePz70XdIJ4DIjvvdLOVR+ZKa5RAn2dj5fInptyC8klHcsL1QlE86L5NMAgO+jo/XFeNQLoqBvfeElBqRj1pPOCwbIgc6Y3pCMHZ8YLe3sXbQB07B1/U887lQ7krteu5xLeV4ufAkox/wgPWNMgd8pl8DdcBygkrb+TFTMMCE8KL9NRortjlmO1fxv/X+munQbdYGjVkXJWFAm5/IWrfn4wTiCOp2korhanJ4Wko7+PFMzdw0M1FCIU0yaC09Dbgf/mNmHewl1aEMq8htlO2u6bBmzkvYGbZbFNToYnb5bW6+mZZtC0JmGbkKT34k4QENgvU3JpTmXM5ylpGddin4B7KtVGAx+WXwMFOEOsApZy8kDrsVGKQ3mLgUD1F4pCut/6kD59Chdt52y/+2qyCqkrzhLXr6sZaZWGXvnVhMFz8z1O+zs2kGZu/QfEhV0tPZbwQfjWUAs//xkJ4wIsifnQXuVhfZrR5XOn5WZ0cj5gswz19WDBKfm3fPvcNoS0u1mRXGM783ofCedIBgUC4nepGSMkggKNPuLWEUS7BhYCs71H/KserSSiz7exglcVFIQaVjf+YteheS7eUzZsuAHKCxsbu/Q==
  template:
    metadata:
      creationTimestamp: null
      name: app
      namespace: prod
    type: Opaque

