kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
rules:
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - deployments
    resourceNames:
      - app
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
      - extensions
    resources:
      - services
    resourceNames:
      - app-service
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
subjects:
  - kind: ServiceAccount
    name: cicd-user
roleRef:
  kind: Role
  name: cicd-role
  apiGroup: rbac.authorization.k8s.io
