kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-preview-role
rules:
  - apiGroups:
      - "*"
    resources:
      - deployments
      - ingresses
      - services
    verbs:
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-preview-role
subjects:
  - kind: ServiceAccount
    name: cicd-user
roleRef:
  kind: Role
  name: cicd-preview-role
  apiGroup: rbac.authorization.k8s.io
