apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-ingress
  annotations:
    spec.ingressClassName: nginx
    cert-manager.io/cluster-issuer: frontend-v1-letsencrypt

spec:
  tls:
    - hosts:
      - "*.herams-stg.org"
      - herams-stg.org
      secretName: frontend-v1-letsencrypt
  rules:
  - host: www.herams-stg.org
    http:
      paths:
      - backend:
          service:
            name: app-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: weblate.herams-stg.org
    http:
      paths:
        - backend:
            service:
              name: weblate-service
              port:
                number: 80
          pathType: ImplementationSpecific
  - host: herams-stg.org
    http:
      paths:
      - backend:
          service:
            name: app-service
            port:
              number: 80
        pathType: ImplementationSpecific
  - host: api.herams-stg.org
    http:
      paths:
        - backend:
            service:
              name: v1api-service
              port:
                number: 80
          pathType: Prefix
          path: /
