apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-12
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
