apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app
  namespace: staging
spec:
  encryptedData:
    cookie_validation_key: AgCbr/e7M2L5FjLV9W1FCZKrJvAXov6EYfHAJt75RM76n/UcBCBIx8oqZvJNq3cMWZxo3KPGyW3oBOLS0Mx7YuBviYSKHozLST6y/nhUd3Xs3IBdwDDkUSHrh9tHWYN4ogM8+fOffXAxVKV3fzPm1jaYIWwohX5zw+TpnmdMhtSIg3wVDBJzlGDOgY22aNgYm6BGzgCTOUbiwjE4euq4rWjwYR/oEoFag0Jj5Wc36xQ9UnM0ATOiVhX+7UiHNwbXPxhQXxGeMFZyvQoPeqNOtVlcbhr56OqlMaJAmbsbbzHtg3NlalAmOZG1qASqfebrJc16eO1j0vMwEsErElNhhbWOSsfX36iXSHxWPxGWenj9AH49WFdu5O4mYFSWVRpmWqFVdvplxg/WD5iAmiGJTxFLHdprM9AhuNmZ1teN+5f+keeiK+jIZaY2BOii2aBVfVAmYlTHS4XS1PdqZMIJ1ZUEyGdCe7QbDGqefNg/6PFNuXBNg7sY2A/RLW951hBlCbiL4POmRAZ2uqJiU9qeKxUdVN6AUgn3dAqDNrmaz6CldZW+mjrob57UhD0ntc/Zfr3xG0LaEkYLbx8fpK7HbvChgAuuBZIwSqxVLf0WUViWmXN71UKjF/6AyDUzfPEsvn6UbYJHs/KWKEtix4WdHt7pXP5FwBbNECHKhXuiTSxBo/YqffLlFRC3SYMIOA8b46nbE7iA4tyQwAKOC3xC3QQ+shPqhvdOlkZcukxYyagojymfu0llpg/6Y80RA03Uj9Hm2EIygjNzDkMsvnYILKtcPQUecgKT695QMECg4dS2/72fTutH3/9XMdi/VO4VXJzvNd9esGEd2e2rYyUMiw+Gt1Yv3a/o3+ZS/QdHsW4anw==
    url_signer_secret: AgCty1UmlmGiaonOsP4UIrsKXPHaO4AqIUxD56njuWTKhp/ZHqpEXEK+s1SSKSxe3t9hvyP1+9pLV7lYdD5Izg4yj7UrwcZi6s7XFPhDDJbctFN4NmQhIrXipnm048H6uQlTK4zcSyTR9bGqA97+TCgjIDZqnrFYIcNFDEUpFC74oUK7hbQVPQdxyKp9WciF3NeCPMmnL0GutaHhsJUNjUjND+cLthFNAnSjYVfzC6vdEhRnRX1P8/CqJLHhZaIE6x8xjff9TN0VtM/wJ7zqZYkF4vcsyUzmuSKTiP2F+eCZ8XuaqJfrca4bh5wEElteqK7v4spHGrmTwPn8+ie/X3msSqI/0/4PHK+jSJLTKLwh4IS9ZOXh5zdmVwTkkVQYPadWKKeeHULhx9/qpptYgsHvB0K4zJ+Mr2a2VoLAaG6g/DwV8TpFA0hNBzxbt1ca0QGKqkdY35hxwah7kz24fEWHOwTOamtSBSHxv/qXND8m3Ct+htrDL3dY0Ia33JIcdKY857A00DIlD1U9SGlKhxMICdyXkKCdGhn44DXCE6GQdiLOl6lGFVSnmNeb+kTTDZ4DvmFnCTINFuoswN7/qDV3sfg589rBl2a6qRkt00oZFro7foKiUC5wW4XFEa2GPQXuWrVSDTve1+yM5bMD6uVRHye4/22ztLcMHdFr0VSccMCYdjVEZgEdI5dnU9YePB1FQ5Jx5ZbqWrA7n8Mz6EYM0omkOG8WeqxNJ9sqHOh2xswFDGUVEF3gh/dy5k7mL/aVEo1x2lYVAy1xovMRFbMywuk7KxnaCBE+QVVGWZ9m4ZYHXFYwIjzG2FFMK5Lmhk8IYqb536QeVskznX/zn+Xw1hBx5Ee96VpRfqGfIA3p0A==
  template:
    metadata:
      creationTimestamp: null
      name: app
      namespace: staging
    type: Opaque

