kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
rules:
  - apiGroups:
      - "*"
    resources:
      - persistentvolumeclaims
      - deployments
      - configmaps
      - ingresses
      - statefulsets
      - services
      - sealedsecrets
      - namespaces
      - cronjobs
    verbs:
      - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-user
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cicd-role
subjects:
  - kind: ServiceAccount
    name: cicd-user
roleRef:
  kind: Role
  name: cicd-role
  apiGroup: rbac.authorization.k8s.io
