SET FOREIGN_KEY_CHECKS=0;
SET NAMES 'utf8';
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (1, 'Overview', 1, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (3, 'Infrastructure', 1, NULL, 1);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (4, 'Basic Amenities', 1, NULL, 6);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (5, 'Service Availability', 1, NULL, 13);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (6, 'Condition', 1, NULL, 2);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (7, 'Functionality', 1, NULL, 3);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (8, 'Accessibility', 1, NULL, 4);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (9, 'Management & Support', 1, NULL, 5);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`) VALUES (10, 'Overview', 1, 5, 0);
SET FOREIGN_KEY_CHECKS=1;
