SET FOREIGN_KEY_CHECKS=0;
SET NAMES 'utf8';
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (1, 'Overview', 1, NULL, 0, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (3, 'Infrastructure', 1, NULL, 1, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (4, 'Basic Amenities', 1, NULL, 6, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (5, 'Service Availability', 1, NULL, 13, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (6, 'Condition', 1, NULL, 2, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (7, 'Functionality', 1, NULL, 3, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (8, 'Accessibility', 1, NULL, 4, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (9, 'Management & Support', 1, NULL, 5, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (10, 'Overview', 1, 5, 0, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (12, 'Overview', 2, NULL, 0, 0);
INSERT INTO `prime2_page` (`id`, `title`, `tool_id`, `parent_id`, `sort`, `add_services`) VALUES (13, 'Suboverview', 1, 1, 0, 0);
SET FOREIGN_KEY_CHECKS=1;
