SET FOREIGN_KEY_CHECKS=0;
SET NAMES 'utf8';
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.close', '\"stop\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.configuration', '\"wrench\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.download', '\"asterisk\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.globalMonitor', '\"globe\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.limeSurveyUpdate', '\"pencil\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.logIn', '\"log-in\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.logOut', '\"log-out\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.open', '\"play\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.preview', '\"file\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.projects', '\"tasks\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.read', '\"eye-open\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.remove', '\"trash\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.reports', '\"file\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.request', '\"forward\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.requestAccess', '\"info-sign\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.search', '\"search\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.share', '\"share\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.update', '\"cog\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.user', '\"user\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('icons.userLists', '\"bullhorn\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('limeSurvey.host', '\"https:\\/\\/ls.herams.org\\/admin\\/remotecontrol\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('limeSurvey.password', '\"pEk6%gW2\\/jYu\"');
INSERT INTO `prime2_setting` (`key`, `value`) VALUES ('limeSurvey.username', '\"herams\"');
SET FOREIGN_KEY_CHECKS=1;
