SET FOREIGN_KEY_CHECKS=0;
SET NAMES 'utf8';
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (12, 'Overview', 5, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (13, 'test', 6, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (14, 'test', 7, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (15, 'Overview', 8, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (69, 'test', 9, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (79, 'Overview', 1, NULL, 0);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (80, 'Infrastructure', 1, NULL, 1);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (81, 'Condition', 1, NULL, 2);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (82, 'Functionality', 1, NULL, 3);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (83, 'Accessibility', 1, NULL, 4);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (84, 'Management & Support', 1, NULL, 5);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (85, 'Basic Amenities', 1, NULL, 6);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (86, 'Service Availability', 1, NULL, 13);
INSERT INTO `prime2_page` (`id`, `title`, `project_id`, `parent_id`, `sort`) VALUES (87, 'Overview', 1, 86, 7);
SET FOREIGN_KEY_CHECKS=1;
