<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(not set)' => '',
    'Account' => '',
    'Account settings' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Are you sure?' => '',
    'Become this user' => '',
    'Block' => '',
    'Block status' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmed' => '',
    'Connect' => '',
    'Disconnect' => '',
    'Generate and send new password to user' => '',
    'Hello' => '',
    'If you cannot click the link, please try pasting the text into your browser' => '',
    'If you did not make this request you can ignore this email' => '',
    'If you don\'t want to change your password or didn\'t request this, just ignore and delete this message' => '',
    'In order to complete your registration, please click the link below' => '',
    'In order to complete your request, please click the link below' => '',
    'Manage users' => '',
    'Networks' => '',
    'Please click the link below to complete your password reset' => '',
    'Please use the following link to log in' => '',
    'Profile' => '',
    'Profile settings' => '',
    'Thank you for signing up on {0}' => '',
    'The HeRAMS Team' => '',
    'The Prime Team' => '',
    'This email address has already been taken' => '',
    'To activate your account please follow this link:' => '',
    'To keep your account secure, please don\'t forward this email to anyone' => '',
    'To reset your password please follow this link:' => '',
    'Unblock' => '',
    'Update' => '',
    'We have generated a password for you' => '',
    'We have received a request to change the email address for your account on {0}' => '',
    'We have received a request to reset the password for your account on {0}' => '',
    'We have received a request to reset your {0} password' => '',
    'Welcome to {0}, the Health Resources and Services Availability Monitoring System' => '',
    'You can connect multiple accounts to be able to log in using them' => '',
    'You have successfully registered to {0}, Health Resources and Services Availability Monitoring System' => '',
    'Your account on {0} has been created' => '',
    'Your {0} account has successfully been activated.' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
    '{0}: Password reset' => '',
    '{0}: Your account has successfully been activated!' => '',
];
