name: Deploy to prod
on:
  push:
    branches:
      - k8s-prod
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer install --ignore-platform-reqs
      - run: docker-compose build
      - run: docker network create devproxy
      - run: cp .env.default .env
      - run: docker-compose run --rm codeception run
      - run: composer stan
  deploy:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.PROD_K8S_SECRET }}
      - name: get_manifests
        run: echo manifests=$(ls k8s/shared/*.yaml k8s/prod/*.yaml | tr "\n" ",") >> $GITHUB_ENV
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'prod'
          manifests: ${{ env.manifests }}
          images: |
            ghcr.io/herams-who/herams-backend/app:prod-${{ github.sha }}
          kubectl-version: 'latest'
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer install --ignore-platform-reqs
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          context: .
          file: docker/app/Dockerfile
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/herams-who/herams-backend/app:prod-${{ github.sha }}