name: Deploy to prod
on:
  push:
    branches:
      - k8s-prod
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '8.1' # Modify this according to your required PHP version.
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Fetch highest stable version of Composer 2.2.*
        run: |
          LATEST_2_2_VERSION=$(curl -s https://packagist.org/packages/composer/composer.json | python -c "
          import sys, json
          versions = [v for v in json.load(sys.stdin)['package']['versions'].keys() if v.startswith('2.2.') and '-dev' not in v and '-alpha' not in v and '-beta' not in v and '-RC' not in v]
          versions.sort(key=lambda s: list(map(int, s.split('.'))))
          print(versions[-1])
          ")
          echo "LATEST_2_2_VERSION=$LATEST_2_2_VERSION" >> $GITHUB_ENV
  
      # Use $LATEST_2_2_VERSION in subsequent steps as needed
      - name: Update Composer to the fetched version
        run: composer self-update $LATEST_2_2_VERSION      
      - run: composer global require "squizlabs/php_codesniffer=3.*"
      - run: composer install --ignore-platform-reqs
      - run: docker-compose build
      - run: docker network create devproxy2
      - run: cp .env.default .env
      - run: docker-compose run --rm codeception run
      - run: composer stan
  deploy:
    needs:
      - build
      - test
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to kubernetes
        uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.PROD_K8S_SECRET }}
      - name: get_manifests
        run: echo manifests=$(ls k8s/shared/*.yaml k8s/prod/*.yaml | tr "\n" ",") >> $GITHUB_ENV
      - uses: Azure/k8s-deploy@v1
        with:
          namespace: 'prod'
          manifests: ${{ env.manifests }}
          images: |
            ghcr.io/herams-who/herams-backend/app:prod-${{ github.sha }}
          kubectl-version: 'latest'
  build:
    name: Build container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '8.1' # Modify this according to your required PHP version.
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Fetch highest stable version of Composer 2.2.*
        run: |
          LATEST_2_2_VERSION=$(curl -s https://packagist.org/packages/composer/composer.json | python -c "
          import sys, json
          versions = [v for v in json.load(sys.stdin)['package']['versions'].keys() if v.startswith('2.2.') and '-dev' not in v and '-alpha' not in v and '-beta' not in v and '-RC' not in v]
          versions.sort(key=lambda s: list(map(int, s.split('.'))))
          print(versions[-1])
          ")
          echo "LATEST_2_2_VERSION=$LATEST_2_2_VERSION" >> $GITHUB_ENV
  
      # Use $LATEST_2_2_VERSION in subsequent steps as needed
      - name: Update Composer to the fetched version
        run: composer self-update $LATEST_2_2_VERSION
      - run: composer global require "squizlabs/php_codesniffer=3.*"
      - run: composer install --ignore-platform-reqs
      - run: composer update herams/i18n --ignore-platform-reqs --no-cache --no-scripts --with-all-dependencies
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.9.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          push: true
          context: .
          file: docker/app/Dockerfile
          build-args: |
            COMMIT_SHA=${{ github.sha }}
          tags: |
            ghcr.io/herams-who/herams-backend/app:prod-${{ github.sha }}
