name: Static Analysis
on:
  pull_request:
jobs:
  static-analysis-psalm:
    name: Static Analysis with Psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - run: composer global require "--dev vimeo/psalm"
      - run: |
          ls ${{ github.workspace }}
      - run: ~/.composer/vendor/bin/psalm --root=protected --use-baseline=./psalm-baseline2.xml -c=./psalm.xml
