name: Push messages to i18n repo
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: 'WorldHealthOrganization/herams-i18n'
          path: 'herams-i18n'
          ssh-key: ${{ secrets.i18n_private_key }}
        name: Checkout i18n repo
      - name: Install composer parallel install
        run: composer global require hirak/prestissimo
      - name: Install composer deps
        run: composer install --no-dev
      - name: Extract translations
        run: protected/yiic message/extract protected/config/i18n.php --message-path .
        # Fix bad Yii header in pot file by copying header from another file
      - name: Create app.pot
        run: (echo 'msgid ""'; echo 'msgstr ""'; grep '^"' index.pot; tail -n +12 ../messages.pot) > app.pot
        working-directory: herams-i18n
      - name: Show git status
        run: git status
        working-directory: herams-i18n