name: Run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: cp .env.default .env
      - run: docker-compose build
      - run: docker-compose run --rm codeception run --coverage-xml
      - run: get https://scrutinizer-ci.com/ocular.phar
      - run: php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
