name: Run tests
on:
  pull_request:
    branches: [ master ]
jobs:
  style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer global require "squizlabs/php_codesniffer=*"
      - run: git fetch origin master --depth 1
      - run: git diff --diff-filter=d --name-only origin/master | xargs ~/.composer/vendor/bin/phpcs
